blank_issues_enabled: false

contact_links:
  - name: Get help on the Discord server
    url: https://discord.gg/BdbUf7VKYC
    about: Want to confirm your issue, or want to just quickly suggest a feature, do it on Discord ;)

