name: Release build Windows
run-name: Release build for Windows
on: 
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Select the build target'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
          - both
        
jobs:
  windows-build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm ffmpeg git bash yasm python python-pip scons gcc diffutils make mingw-w64
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # DEBUG BUILDS
      - name: Build Windows Debug video only
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        run: scons -j4 target=template_debug platform=windows arch=x86_64 use_system=no enable_gpl=yes enable_small=yes
      - name: Uploading GDExtension artifact debug video only
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: windows_video_only_template_debug
          path: bin/windows_video_only_template_debug

      - name: Build Windows Debug
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        run: scons -j4 target=template_debug platform=windows arch=x86_64 use_system=no enable_gpl=yes recompile_ffmpeg=no include_renderer=yes enable_small=yes
      - name: Uploading GDExtension artifact debug
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: windows_template_debug
          path: bin/windows_template_debug

      # RELEASE BUILDS
      - name: Build Windows Release video only
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        run: scons -j4 target=template_release platform=windows arch=x86_64 use_system=no enable_gpl=yes recompile_ffmpeg=no enable_small=yes
      - name: Uploading GDExtension artifact release video only
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: windows_video_only_template_release 
          path: bin/windows_video_only_template_release

      - name: Build Windows Release
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        run: scons -j4 target=template_release platform=windows arch=x86_64 use_system=no enable_gpl=yes recompile_ffmpeg=no include_renderer=yes enable_small=yes
      - name: Uploading GDExtension artifact release
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: windows_template_release
          path: bin/windows_template_release
