name: Release build Windows
run-name: Release build for Windows
on: [workflow_dispatch]
jobs:
  windows-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install MSYS2
        run: sudo apt-get update && sudo apt-get install gcc-mingw-w64
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Setup SCons
        run: pip install scons  
      - name: Install Mingw
        run: |
          sudo apt-get update
          sudo apt-get install mingw-w64
          sudo update-alternatives --config x86_64-w64-mingw32-gcc <<< "1"
          sudo update-alternatives --config x86_64-w64-mingw32-g++ <<< "1"
      - name: Install Yasm
        run: sudo apt-get install -y yasm

      - name: Build Windows Debug video only
        run: scons -j4 target=template_debug platform=windows arch=x86_64 use_system=no enable_gpl=yes enable_small=yes
      - name: Build Windows Debug
        run: scons -j4 target=template_debug platform=windows arch=x86_64 use_system=no enable_gpl=yes recompile_ffmpeg=no include_renderer=yes enable_small=yes
      - name: Build Windows Release video only
        run: scons -j4 target=template_release platform=windows arch=x86_64 use_system=no enable_gpl=yes recompile_ffmpeg=no enable_small=yes
      - name: Build Windows Release
        run: scons -j4 target=template_release platform=windows arch=x86_64 use_system=no enable_gpl=yes recompile_ffmpeg=no include_renderer=yes enable_small=yes

      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-windows-debug-video_only
          path: bin/windows_video_only_template_debug
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-windows-debug
          path: bin/windows_template_debug
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-windows-release-video-only
          path: bin/windows_video_only_template_release
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-windows-release
          path: bin/windows_template_release
