name: Release build linux
run-name: Release build for Linux
on: [workflow_dispatch]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install FFmpeg
        run: |
          sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg6
          sudo apt-get update
          sudo apt-get install ffmpeg
      - name: Install FFmpeg devs
        run: |
          sudo apt-get install libswscale-dev
          sudo apt-get install libswresample-dev
          sudo apt-get install libavutil-dev
          sudo apt-get install libavformat-dev
          sudo apt-get install libavfilter-dev
          sudo apt-get install libavdevice-dev
          sudo apt-get install libavcodec-dev
      - name: Check FFmpeg Version
        run: ffmpeg -version
      - name: Add FFmpeg libs
        run: echo "FFMPEG_INCLUDES=/usr/include/x86_64-linux-gnu" >> $GITHUB_ENV
      - name: Setup SCons
        run: pip install scons
      - name: Install Yasm
        run: sudo apt-get update && sudo apt-get install -y yasm
        
      # DEBUG BUILDS
      - name: Build Linux Debug video only
        run: scons -Q -j4 target=template_debug platform=linux arch=x86_64 use_system=yes
      - name: Build Linux Debug
        run: scons -Q -j4 target=template_debug platform=linux arch=x86_64 use_system=yes include_renderer=yes

      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-debug-video-only
          path: bin/linux_video_only_template_debug
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-debug
          path: bin/linux_template_debug
          
      # RELEASE builds
      - name: Build Linux Release video only
        run: scons -j4 target=template_release platform=linux arch=x86_64 use_system=yes
      - name: Build Linux Release
        run: scons -j4 target=template_release platform=linux arch=x86_64 use_system=yes include_renderer=yes

      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-release-video-only
          path: bin/linux_video_only_template_release
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-release
          path: bin/linux_template_release
