name: Build GDE GoZen - Video only
run-name: Build Video only  
on: [workflow_dispatch]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install FFmpeg
        run: |
          sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg6
          sudo apt-get update
          sudo apt-get install ffmpeg
      - name: Install FFmpeg devs
        run: |
          sudo apt-get install libswscale-dev
          sudo apt-get install libswresample-dev
          sudo apt-get install libavutil-dev
          sudo apt-get install libavformat-dev
          sudo apt-get install libavfilter-dev
          sudo apt-get install libavdevice-dev
          sudo apt-get install libavcodec-dev
      - name: Check FFmpeg Version
        run: ffmpeg -version
      - name: Add FFmpeg libs
        run: echo "FFMPEG_INCLUDES=/usr/include/x86_64-linux-gnu" >> $GITHUB_ENV
      - name: Setup SCons
        run: pip install scons
      - name: Install Yasm
        run: sudo apt-get update && sudo apt-get install -y yasm
        
      - name: Build Linux Debug
        run: scons -Q -j4 target=template_debug platform=linux arch=x86_64 use_system=yes
      - name: Build Linux full Debug
        run: scons -Q -j4 target=template_debug platform=linux arch=x86_64 use_system=no enable_gpl=yes enable_small=yes
      - name: Build Linux Release
        run: scons -Q -j4 target=template_release platform=linux arch=x86_64 use_system=yes
      - name: Build Linux full Release
        run: scons -Q -j4 target=template_release platform=linux arch=x86_64 use_system=no enable_gpl=yes recompile_ffmpeg=no enable_small=yes

      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-debug
          path: bin/linux_video_only_template_debug/*
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-full-debug
          path: bin/linux_video_only_full_template_debug/*
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-release
          path: bin/linux_video_only_template_release/*
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-full-release
          path: bin/linux_video_only_full_template_release/*
  windows-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install MSYS2
        run: sudo apt-get update && sudo apt-get install gcc-mingw-w64
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Setup SCons
        run: pip install scons
      - name: Install Mingw
        run: |
          sudo apt-get update
          sudo apt-get install mingw-w64
          sudo update-alternatives --config x86_64-w64-mingw32-gcc <<< "1"
          sudo update-alternatives --config x86_64-w64-mingw32-g++ <<< "1"
      - name: Install Yasm
        run: sudo apt-get install -y yasm

      - name: Build Windows Debug
        run: scons -Q -j4 target=template_debug platform=windows arch=x86_64 use_system=no enable_gpl=yes
      - name: Build Windows Release
        run: scons -Q -j4 target=template_release platform=windows arch=x86_64 use_system=no enable_gpl=yes recompile_ffmpeg=no

      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-windows-debug
          path: bin/windows_video_only_template_debug/*
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-windows-release
          path: bin/windows_video_only_template_release/*
