name: Video editor build
run-name: GoZen Video Editor gdextension build
on: [workflow_dispatch]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    container: voylin/gde_gozen:latest
    steps:
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Installing dependencies and building
        run: |
          scons -j4 target=template_debug platform=linux arch=x86_64 use_system=yes include_renderer=yes
          scons -j4 target=template_debug platform=linux arch=x86_64 use_system=no enable_gpl=yes include_renderer=yes enable_small=yes
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-debug
          path: bin/linux_template_debug
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-linux-full-debug
          path: bin/linux_full_template_debug
  windows-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install MSYS2
        run: sudo apt-get update && sudo apt-get install gcc-mingw-w64
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Setup SCons
        run: pip install scons  
      - name: Install dependencies and building
        run: |
          sudo apt-get update
          sudo apt-get install mingw-w64
          sudo update-alternatives --config x86_64-w64-mingw32-gcc <<< "1"
          sudo update-alternatives --config x86_64-w64-mingw32-g++ <<< "1"
          sudo apt-get install -y yasm
          scons -j4 target=template_debug platform=windows arch=x86_64 use_system=no enable_gpl=yes recompile_ffmpeg=yes include_renderer=yes enable_small=yes
      - name: Uploading GDExtension artifact
        uses: actions/upload-artifact@v4
        with:
          name: gde_gozen-windows-debug
          path: bin/windows_template_debug
