name: Video editor build
run-name: GoZen Video Editor gdextension build
on: 
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Select the build target'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
          - both
      job_target:
        description: 'Select the platform'
        required: true
        default: 'linux'
        type: choice
        options:
          - linux
          - windows
          - both

jobs:
  linux-build:
    if: ${{ github.event.inputs.job_target == 'linux' || github.event.inputs.job_target == 'both' }}
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm ffmpeg git bash yasm python python-pip scons gcc diffutils make
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # DEBUG BUILDS
      - name: Building debug Linux
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        run: scons -j4 target=template_debug platform=linux arch=x86_64 use_system=yes include_renderer=yes dev_build=yes
      - name: Uploading GDExtension artifact debug
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux_template_debug
          path: bin/linux_template_debug

      - name: Building debug Linux full
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        run: scons -j4 target=template_debug platform=linux arch=x86_64 use_system=no enable_gpl=yes include_renderer=yes enable_small=yes dev_build=yes
      - name: Uploading GDExtension artifact full debug
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux_template_debug_full
          path: bin/linux_full_template_debug

        # RELEASE BUILDS
      - name: Building release Linux
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        run: scons -j4 target=template_release platform=linux arch=x86_64 use_system=yes include_renderer=yes
      - name: Uploading GDExtension artifact release
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux_template_release
          path: bin/linux_template_release

      - name: Building release Linux full
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        run: scons -j4 target=template_release platform=linux arch=x86_64 use_system=no enable_gpl=yes include_renderer=yes enable_small=yes
      - name: Uploading GDExtension artifact full release
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux_template_release_full
          path: bin/linux_full_template_release

  windows-build:
    if: ${{ github.event.inputs.job_target == 'windows' || github.event.inputs.job_target == 'both' }}
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm ffmpeg git bash yasm python python-pip scons gcc diffutils make mingw-w64
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

        # DEBUG BUILD
      - name: Building debug Windows
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        run: |
          scons -j4 target=template_debug platform=windows arch=x86_64 use_system=no enable_gpl=yes include_renderer=yes enable_small=yes dev_build=yes
      - name: Uploading GDExtension artifact debug
        if: ${{ github.event.inputs.build_target == 'debug' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: windows_template_debug
          path: bin/windows_template_debug

        # RELEASE BUILD
      - name: Building release Windows
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        run: |
          scons -j4 target=template_release platform=windows arch=x86_64 use_system=no enable_gpl=yes include_renderer=yes enable_small=yes
      - name: Uploading GDExtension artifact release
        if: ${{ github.event.inputs.build_target == 'release' || github.event.inputs.build_target == 'both' }}
        uses: actions/upload-artifact@v4
        with:
          name: windows_template_release
          path: bin/windows_template_release
